services:
  postgres:
    image: postgres:15-alpine
    container_name: next_aura_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: next_aura_db
    network_mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
